### ISSUE TITLE
Regex for finding answer will not work when it is most needed

### ISSUE THREAD

**Issue by tomjohnneill** [bcoe/istheshipstillstuck#1]
When the "Yes." changes to "No." the TikTok link will disappear and this will all explode into uselessness.

**Comment by whichsteveyp** [comment]
can you just match `Yes.` from the text and ignore if there is an `<a>` or not, and default to `No.`?

**Comment by bcoe** [comment]
@trivikr just submitted a temporary fix. I think we might need to use machine learning if we're going to get this right.
